### ISSUE TITLE
How to set location if there are duplicates?

### ISSUE THREAD

**Issue by SeanKempf** [mj-jackson/homebridge-simple-weather#4]
**Describe Your Problem:**

When I search my location on OpenWeather, there are two possible matches.  My location is the second match.  How can I have homebridge-simple-weather grab information for that choice instead of the first match which is what it pulls?
**Logs:**
No error in logs.  This may become a feature request

**Plugin Config:**
{
    "language": "en",
    "apiKey": "XXXXXXXXXXXXXXXXXXXXX",
    "location": "Newburgh, US",
    "interval": 60,
    "currentTemp": true,
    "forecastNum": 0,
    "forecastInterval": 6,
    "forecastCurrentTemp": false,
    "forecastMinTemp": false,
    "forecastMaxTemp": false,
    "forecastHumidity": false,
    "forecastRainProb": false,
    "platform": "HomebridgeSimpleWeather"
}

**Screenshots:**
![image](https://user-images.githubusercontent.com/22504662/194565082-4e7187b8-1c25-4606-a95a-225bcba57524.png)

**Environment:**

* **Plugin Version**:2.0.1
* **Homebridge Version**:1.5.0
* **Node.js Version**: 16.14.2
* **NPM Version**: 8.7.0
* **Operating System**:Raspbian

**Comment by mj-jackson** [comment]
Hi!

Currently I am using the (deprecated) city names directly, which does not report that there are multiple hits for a given city name. That is why there are no log outputs for that.

Using the geo API or lat/long directly is on my roadmap, but WIP.

For your problem:
The doc states that searching by city name also accepts state code and country code all separated by comma. So in your example: `Newburgh, NY, US` or `Newburgh, IN, US` should give different results and you can pick the correct one.
https://openweathermap.org/current#name

**Comment by mj-jackson** [comment]
Option to add latitude and longitude is added.
